fix: Ensure Robolectric's super.setUp() is called
Adds in lint check and fixes error message. The lint check enforces
`super.method` if a method is annotated with `@CallSuper`

Previous Error was:

```
java.lang.UnsatisfiedLinkError: 'long net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'
	at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
	...
```

The `Error` is only thrown in the case that Robolectric is used

https://developer.android.com/reference/androidx/annotation/CallSuper