refactor: Convert Storage to Kotlin
com.ichi2.libanki.Storage

Required for migration to new Anki Backend

Collection() method needed a rename due to

```
java.lang.NoSuchMethodError: 'com.ichi2.libanki.Collection com.ichi2.libanki.Storage.Collection$default(com.ichi2.libanki.Storage, android.content.Context, java.lang.String, boolean, boolean, com.ichi2.libanki.utils.Time, int, java.lang.Object)'
```