test: close FragmentScenario after use
fixes OutOfMemoryError: Java heap space

Follow up from 1113858df6a6b8c8c93afac0e1f788942db70c9f

```
CreateDeckDialogTest > searchDecksIconVisibilityDeckCreationTest FAILED
    java.lang.OutOfMemoryError: Java heap space
        at org.robolectric.res.android.CppAssetManager2$Theme.SetTo(CppAssetManager2.java:1700)
        at org.robolectric.shadows.ShadowArscAssetManager10.nativeThemeCopy(ShadowArscAssetManager10.java:1657)
        ...
```

Cause:

https://redirect.github.com/ankidroid/Anki-Android/pull/17495