fix(release): Unable to start activity: MultimediaActivity
Reverts b73ac85ea22f641b8bc3700ff8d36e0c18be97d9

We got the following truncated stack trace due to proguard/minify

Fix it via implementing Parcelize/Parcelable

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.multimedia.MultimediaActivity}: android.os.BadParcelableException: Parcelable encountered IOException reading a Serializable object (name = com.ichi2.anki.multimedia.f)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4377)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4574)
    ...
    at android.os.Looper.loop(Looper.java:393)
    at android.app.ActivityThread.main(ActivityThread.java:9549)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
Caused by: android.os.BadParcelableException: Parcelable encountered IOException reading a Serializable object (name = com.ichi2.anki.multimedia.f)
    at android.os.Parcel.readSerializableInternal(Parcel.java:5410)
    at android.os.Parcel.readValue(Parcel.java:4928)
    at android.os.Parcel.readValue(Parcel.java:4625)
    ...
    at android.os.Bundle.getSerializable(Bundle.java:1283)
    at com.ichi2.compat.CompatV33.getSerializable(CompatV33.kt:47)
    at com.ichi2.compat.CompatHelper$Companion.getSerializableCompat(CompatHelper.java:85)
    at com.ichi2.anki.multimedia.MultimediaActivity.getMultimediaArgsExtra(MultimediaActivity.kt:66)
    at com.ichi2.anki.multimedia.MultimediaActivity.onCreate(MultimediaActivity.kt:96)
    at android.app.Activity.performCreate(Activity.java:9196)
Caused by: java.io.InvalidClassException: m4.d; no valid constructor
    at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:163)
    at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:832)
```

Fixes 18712