test: Fix CurrentTimeMillisUsage lint
We can ignore this one as it's in tests

Error: Use the collection's getTime() method
 instead of System.currentTimeMillis()

[DirectSystemCurrentTimeMillisUsage from com.ichi2.anki.lint]

Issue 10322 - lint failed on androidTest