chore: convert DeckPicker to ViewBinding
We do not use `by viewBinding` here due to how 'NavigationDrawerActivity'
updates the view hierarchy

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki.debug/com.ichi2.anki.DeckPicker}: java.lang.ClassCastException: androidx.drawerlayout.widget.ClosableDrawerLayout cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	...
Caused by: java.lang.ClassCastException: androidx.drawerlayout.widget.ClosableDrawerLayout cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout
	at com.ichi2.anki.databinding.HomescreenBinding.bind(HomescreenBinding.java:130)
	at com.ichi2.anki.DeckPicker$special$$inlined$viewBindingActivityWithCallbacks$default$1.invoke(ActivityViewBindings.kt:162)
	at com.ichi2.anki.DeckPicker$special$$inlined$viewBindingActivityWithCallbacks$default$1.invoke(ActivityViewBindings.kt:141)
	at dev.androidbroadcast.vbpd.LazyViewBindingProperty.getValue(ViewBindingProperty.kt:78)
	at dev.androidbroadcast.vbpd.ActivityViewBindingProperty.getValue(ActivityViewBindings.kt:62)
	at dev.androidbroadcast.vbpd.ActivityViewBindingProperty.getValue(ActivityViewBindings.kt:50)
	at com.ichi2.anki.DeckPicker.getBinding(DeckPicker.kt:254)
	at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.kt:534)
	...
```

Issue 11116