fix: videos with only audio stream
A number of video extension may only contain audio

In these cases, we should show a play button

Sources:
* anki-15872-valid-1.mp4 -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media/movie_5.mp4
* anki-15872-audio-only.webm -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media/test-a-128k-44100Hz-1ch.webm
* anki-15872-audio-only.mp4 -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media-source/mp4/test-a-128k-44100Hz-1ch.mp4

I attempted to use MediaMetadataRetriever:

```
MediaMetadataRetriever().let {
    it.setDataSource(file.path)
    it.extractMetadata(MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO)
}
```

but it fails on API 23 with:

```
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
at android.media.MediaMetadataRetriever.setDataSource(Native Method)
```

Fixes 15872

Co-authored-by: Brayan Oliveira <69634269+brayandso@users.noreply.github.com>
(cherry picked from commit c8ec679acdcdf5d8d55b421c276bcd86b5253409)