fix(card-browser): incorrect 'notes' sort order
Issue: when moving to 'cards or notes'
We used 'sortType' instead of 'noteSortType'

Then when we loaded it from the collection, it caused problems

Caused:

```
com.ichi2.libanki.exception.InvalidSearchException: net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: Can't sort Notes by Custom.
  	at com.ichi2.libanki.Collection.findNotes(Collection.kt:398)
```

Fixes 16514