fix: [maybe] NullPointerException on subscriber.get() (#16228)
* fix: [maybe] NullPointerException on `subscriber.get()`

I could not diagnose this issue visually.

I strongly suspect it is a threading issue as `mutableListOf` = `ArrayList`
which is not thread safe

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
	at com.ichi2.libanki.ChangeManager.notifySubscribers(SourceFile:24)
	at com.ichi2.libanki.ChangeManager.notifySubscribers$AnkiDroid_fullRelease(SourceFile:65)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invokeSuspend(SourceFile:17)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:2)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:1)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:8)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:54)
	at kotlinx.coroutines.BuildersKt.withContext(SourceFile:1)
	at com.ichi2.libanki.ChangeManagerKt.undoableOp(SourceFile:96)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$1.invokeSuspend(Unknown Source:10)
```