Convert import/export to commons-compress
Allows import of apkg >2GB.

new java.util.zip.ZipFile() failed with:

java.util.zip.ZipException: error in opening zip file

This was done in the export side to keep library use consistent

Sadly, syncing uses `ZipFile.OPEN_READ | ZipFile.OPEN_DELETE`,
and there does not seem to be a direct replacement in the library
so I've kept this as using java.util.zip for now.

Fixes 6419