chore: fix layout names for viewBinding
* cardbrowser -> card_browser_fragment
  * card_browser already existed
* card_browser_searchview -> card_browser_searchview_fragment
  * cardbrowser_searchview already existed

Due to a bug in the implementation and our unusual names,
class names were incorrectly generated:
`CardBrowserSearchviewBinding` defined `CardbrowserSearchviewBinding`
as the casing of 'Browser' differed, this caused a compile error

```
build/generated/data_binding_base_class_source_out/fullDebug/out/com/ichi2/anki/databinding/CardBrowserSearchviewBinding.java:25: error: class CardbrowserSearchviewBinding is public, should be declared in a file named CardbrowserSearchviewBinding.java
public final class CardbrowserSearchviewBinding implements ViewBinding {
```

Issue 11116