fix(manage-space): crash if `getPackageSizeInfo` fails
On a (knockoff?) API 25 phone, `getPackageSizeInfo` failed with

```
java.lang.NoSuchMethodException: getPackageSizeInfo [class java.lang.String, interface b.a]
	at java.lang.Class.getMethod(Class.java:1981)
	at java.lang.Class.getMethod(Class.java:1637)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingGetPackageSizeInfo(FileUtils.kt:115)
```

We fix this via:

* handling the exception
* documenting the exception

Fixes 17387

(cherry picked from commit 3ed3bda30b3547f078e84ff35c2910676a4826f0)