chore(deps): bump androidGradlePlugin from 8.5.2 to 8.6.0
! This change requires Android Studio Koala Feature Drop

We fix the following error with a `SuppressLint` annotation.
The code converts a valid int to a long (as the caller requests a long)
but this long is not detected as valid

```
AddContentApi.kt:553: Error: Must be one or more of:
PackageManager.GET_META_DATA, PackageManager.GET_SHARED_LIBRARY_FILES, ...,
PackageManager.GET_UNINSTALLED_PACKAGES [WrongConstant]
                              PackageManager.GET_META_DATA.toLong()
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Bumps `androidGradlePlugin` from 8.5.2 to 8.6.0.

Updates `com.android.application` from 8.5.2 to 8.6.0

Updates `com.android.library` from 8.5.2 to 8.6.0

---
updated-dependencies:
- dependency-name: com.android.application
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.android.library
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>