chore: remove runOnUiThread in CardBrowser
This was only required for tests and was a bug

Sample error when this bug occurred

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9619)
```

and after an attempted fix (on Windows):

```
    java.lang.RuntimeException: Can't create handler inside thread Thread[...] that has not called Looper.prepare()
        at android.os.Handler.__constructor__(Handler.java:227)
```