MoveDirectory: remove 'attemptRename' & fix for 'MoveFile'
This hasn't worked for directories on any of my devices:

```
Recovering failed rename /storage/emulated/0/AnkiDroid/collection.media to /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid20/collection.media

Rename recovery failed
        android.system.ErrnoException: rename failed: EXDEV (Cross-device link)
            at libcore.io.Linux.rename(Native Method)
            ...
```

We previously assumed this would fail for a directory first.
So did not set `attemptRename` to false for a file copy.

Now we no longer handle directories, so set this value on a file copy.