test: ignore flaky tests
```
    androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: an instance of android.widget.TextView and view.getText() with or without transformation to match: is "⁨1⁩ note updated."
    If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:androidx.appcompat.widget.AppCompatSpinner{3b905b2 VFED..CL. ......ID 56,0-232,64 #7f0a04e2 app:id/toolbar_spinner}
 ```

 etc...