test(deps): Add org.json.json
This allows us to use JSONObject and others in JvmTests

Because this avoid Robolectric, we get a significant speedup

fixes error:

```
Method put in org.json.JSONObject not mocked. See https://developer.android.com/r/studio-ui/build/not-mocked for details.
java.lang.RuntimeException: Method put in org.json.JSONObject not mocked. See https://developer.android.com/r/studio-ui/build/not-mocked for details.
	at org.json.JSONObject.put(JSONObject.java)
```

This causes issues in tests with JSONWriter's API being different
so rewrite test code to avoid using it

issue:

```
'org.json.JSONWriter org.json.JSONStringer.object()'
java.lang.NoSuchMethodError: 'org.json.JSONWriter org.json.JSONStringer.object()'
	at com.ichi2.testutils.JsonUtils.writeTo(JsonUtils.kt:64)
```