fix: emulator tests (BuildConfig)
0c238ed9bbf783708fdcf7eb5125c1a9cc8a8d64 broke with

```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithRuntimeError[test(AVD) - 11] FAILED
	java.lang.AssertionError: View assertion was not true within 30000 milliseconds
	at org.junit.Assert.fail(Assert.java:89)
E0201 20:37:37.824023 bcf7000 FrameBuffer.cpp:3765] Failed to find ColorBuffer:314

com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED
	java.lang.AssertionError: View assertion was not true within 30000 milliseconds
	at org.junit.Assert.fail(Assert.java:89)
```

But only when run on `main`, not in the PR

I suspect:
The "CI" parameter appeared to not passed to the emulator

So we should use BuildConfig, rather than getenv

ref: https://github.com/ankidroid/Anki-Android/pull/15381#issuecomment-1922257990