avoid compilation error due to backup files by using sed to edit in place without backup
this error occurs without this change:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':AnkiDroid:mergeDebugResources'.
> /Users/mike/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml-e: Error: The file name must end with .xml