fix(test): resetResetAllElementsFromOnboarding
This was broken by an Actions runner update, which changed the order
of running tests.

Global state was not cleared by a test in OnboardingFlagTest

* Add method: resetOnboardingForTesting
* Call resetOnboardingForTesting from Onboarding[Utils/Flag]Test

Error message before fixed
```
java.lang.AssertionError: All onboarding identifiers are available
for reset
Expected: iterable over
["CardBrowserOnboarding", "ReviewerOnboarding", "NoteEditorOnboarding",
 "FirstEnum", "DeckPickerOnboarding"] in any order
     but: No item matches: "FirstEnum" in
["CardBrowserOnboarding", "DeckPickerOnboarding",
"NoteEditorOnboarding", "ReviewerOnboarding"]
```

Fixes 9597