fix: Crash if aborting media sync from notification
```
 java.lang.IllegalArgumentException: View=com.android.internal.policy.DecorView{a35a4f7 V.E...... R......D 0,0-912,533 aid=1073741993}[DeckPicker] not attached to window manager
 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:587)
 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:494)
 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:216)
 	at android.app.Dialog.dismissDialog(Dialog.java:404)
 ```

Fix by a try...catch, which needed to be on the main thread

Fixes 18542