refactor: extract ktlint to version catalog
The issue inside 'subprojects' is:

> * Exception is:
  org.gradle.api.UnknownDomainObjectException: Extension with name 'libs' does not exist. Currently registered extension names: [ext, ktlint]
  	at org.gradle.internal.extensibility.ExtensionsStorage.unknownExtensionException(ExtensionsStorage.java:148)
  	at org.gradle.internal.extensibility.ExtensionsStorage.getByName(ExtensionsStorage.java:125)
  	at org.gradle.internal.extensibility.DefaultConvention.getByName(DefaultConvention.java:187)
  	at org.gradle.kotlin.dsl.accessors.runtime.RuntimeKt.extensionOf(Runtime.kt:35)
  	at Build_gradle$1$1.invoke(build.gradle.kts:36)