NF: More specific exception for useless scroll call (#8844)
* NF: correct lastVisibleItem

Take for example firstVisibleItem = 0, visibleItemCount = 1. Then the last visible item is also 0, that is, 0 + 1 - 1.
With the current notation, we got the first item after the visible items.

It seems that `lastVisibleItem + 1 >= totalItemCount` can never be true. Alas 250c9c3e18732e7fee0e6896cc95e8e4864637ba
do not explain why it was added (and I don't think it's worth asking Tim for an explanation 6 years later)

However, I believe that when it was introduced, this value was actually supposed to represent the last visible item. So
that the new version is actually truthy if the lastVisibleItem is after the totalItemCount.

Since it should never occur unless the list api is broken, it's hard to really be sure what the correct behaviour should
be here. I would think deleting it is what make more sens. But until I know, I prefer the change to remain Nf

* NF: useless scroll more specific

According to Mike, there used to be 5 to 10 report by hour on the beta version. All with
> com.ichi2.anki.exception.ManuallyReportedException: Useless onScroll call, with size 0 firstVisibleItem 0,
> lastVisibleItem 0 and visibleItemCount 0.

This change ensure that we log more specifically case where #8821 could have occured. That is, there are cards but we
are asked to display nothing.

Note that this is not a bug. The fact that `visibleItemCount` is equal to 0 is actually authorized by the method we
override and mentionned in the javadoc. It perfectly makes sens to get this order, since it can be used to know that we
can delete some elements from the cache for example, since nothing is displayed.

It would be interesting to know how often it occurs, but it is not a bug.