test: ignore broken test - fixes macOS CI issue
This broken test caused a hang on macOS arm64, and a crash on macOS x64

**The hang was not detected as an error, this needs fixing**

```
Exception in thread "Test worker"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Test worker"
FAILURE: Build failed with an exception.
```

The issue was a circular dependency (`ClassCircularityError`)
caused by mocking `Collections`

Detected as unit tests weren't finishing on my mac

Related: 13298