test: fix OutOfMemoryError: Java heap space
on macos:

```
at com.ichi2.anki.dialogs.CreateDeckDialogTest.setUp(CreateDeckDialogTest.kt:52)

Caused by:
java.lang.OutOfMemoryError: Java heap space
    at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:77)
    at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:538)
    at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
    at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
    at org.robolectric.shadows.ShadowBitmapFactory.create(ShadowBitmapFactory.java:287)
    at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:189)
    at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:153)
```

https://redirect.github.com/ankidroid/Anki-Android/pull/15520#issuecomment-1948416566